### ISSUE TITLE
Does not work on an Android emulator

### ISSUE THREAD

**Issue by jsphkhan** [feathersjs/feathers-react-native-chat#10]
Socket connections are not made on an Android emulator (Nexus 5 - API 22) whereas it is working fine on iOS simulator. Can you please let me know if I am missing anything.

**Comment by ekryski** [comment]
@jsphkhan it's your IP address most likely. Android doesn't like `localhost`. I've verified that it does work on the GenyMotion emulators. If you run the shell script in the `bin` folder it will copy an `/etc/hosts` file to the android emulator. That should fix it so that localhost from the emulator points to the correct IP. Otherwise you should set your computers' IP address manually.

Let me know if that doesn't work and we can re-open.

**Comment by jsphkhan** [comment]
Thanks a lot. Most probably it is IP. It should be 10.0.2.2 I believe. I will try that.

**Comment by jsphkhan** [comment]
yes it is working now. Thanks once again...
